### ISSUE TITLE
Obsah

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/bachelors-thesis#5]
> Cílem práce je navrhnout a vyvinout multiplatformní mobilní hru, která bude klást důraz na kooperaci více hráčů připojených z různých zařízeních přes síť. Ve hře bude využito specifik moderních mobilních zařízení (například různé typy senzorů a možnosti ovládání). Při práci budou uplatněny tradiční postupy softwarového inženýrství.
> 
> - Proveďte průzkum existujících podobných aplikací a trendů v oblasti mobilních her.
> - Analyzujte a porovnejte vybrané technologie pro vývoj multiplatformních mobilních aplikací.
> - Navrhněte samotnou hru a herní logiku, sestavte požadavky na aplikaci a případy užití.
> - Navrhněte architekturu a uživatelské rozhraní aplikace s důrazem na snadnou rozšiřitelnost a použitelnost.
> - Implementujte a otestujte aplikaci dle návrhu.
> - Vytvořte uživatelskou a vývojářskou dokumentaci.
> - Zhodnoťte výslednou aplikaci a popište námět na rozšíření.

Aktualizovaný stav obsahu práce:

- [x] Poděkování #9 
- [x] Prohlášení
- [x] Abstrakt #10 
  - [x] cs
  - [x] en
- [x] Úvod #11
- [x] Alternativy aplikace (nebo *Konkurenční aplikace* ?) #12 
- [x] Analýza
  - [x] Multiplatformní framework #13
  - [x] State management #14
  - [x] Databáze #15
  - [x] Testování #16
  - [x] Architektura #21 
  - [x] Senzory
- [x] Návrh
  - [x] Popis funkčnosti hry #17 
  - [x] Funkční požadavky #18 
  - [x] Nefunkční požadavky #19 
  - [x] Use Cases #20 
  - [x] UI návrh #34
  - [x] Lokalizace #22 
- [x] Implementace
  - [x] Použité nástroje #23 
  - [x] Ukázka vybrané části #24 
- [x] Testování
  - [x] Typy použitých testů #25 
  - [x] Vybraná ukázka #26 
- [x] Nasazení
  - [x] Android #27 
  - [x] iOS #28 
- [x] Závěr
  - [x] Zhodnocení výsledné aplikace #29 
  - [x] Osobní přínos #30 
  - [x] Námět na rozšíření #31 
- [x] Seznam použitých zkratek #32 
- [x] Obsah přílohy #33

**Comment by tenhobi** [comment]
@MarekSuchanek mohu poprosit o komentář, jestli je takhle rámcový obsah v pořádku nebo mám něco upravit? 🙂

**Comment by MarekSuchanek** [comment]
Rámcově je obsah OK 👍 . Jen bych prohodil požadavky a use case. UC naplňují požadavky, tak je vhodné mít nejdřív definované požadavky. Ideální by bylo tam pak mít i to mapování (v SI1 se to dělalo takovou tabulkou/maticí).
